version: '3'
services:
  db:
    image: postgres:15.4
    container_name: spring-security-with-jpa
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

